import javax.swing.*;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author Victoria
 */
public class MainFrame extends javax.swing.JFrame {
    // Variables declaration - do not modify
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDeleteCancel;
    private javax.swing.JButton jButtonDeleteOk;
    private javax.swing.JButton jButtonEditCancel;
    private javax.swing.JButton jButtonEditOk;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonViewAll;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxFunctional;
    private javax.swing.JComboBox<String> jComboBoxNumber;
    private javax.swing.JComboBox<String> jComboBoxSeats;
    private javax.swing.JComboBox<String> jComboBoxSelectNumber;
    private javax.swing.JComboBox<String> jComboBoxSoftware;
    private javax.swing.JDialog jDialogAddClass;
    private javax.swing.JDialog jDialogDeleteClass;
    private javax.swing.JDialog jDialogEditClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFunctional;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelSeats;
    private javax.swing.JLabel jLabelSoftware;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAdd;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemPrint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelDB;
    private javax.swing.JPanel jPanelFilters;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableTaSamaya;
    private javax.swing.JTextArea jTextAreaEditSoftware;
    private javax.swing.JTextArea jTextAreaSoftware;
    private javax.swing.JTextField jTextFieldEditFunctional;
    private javax.swing.JTextField jTextFieldEditSeats;
    private javax.swing.JTextField jTextFieldFunctional;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldSeats;

    public ArrayList<DataTable> dt=new ArrayList<>();
    public DataAnalyzer da=new DataAnalyzer();
    // End of variables declaration

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        try {
            dt= da.dataUpd();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        java.awt.GridBagConstraints gridBagConstraints;

        jDialogAddClass = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumber = new javax.swing.JTextField();
        jTextFieldSeats = new javax.swing.JTextField();
        jTextFieldFunctional = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSoftware = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jDialogDeleteClass = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonDeleteOk = new javax.swing.JButton();
        jButtonDeleteCancel = new javax.swing.JButton();
        jDialogEditClass = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxSelectNumber = new javax.swing.JComboBox<>();
        jButtonFind = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEditSeats = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEditFunctional = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonEditOk = new javax.swing.JButton();
        jButtonEditCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaEditSoftware = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanelSearch = new javax.swing.JPanel();
        jPanelFilters = new javax.swing.JPanel();
        jLabelNumber = new javax.swing.JLabel();
        jLabelFunctional = new javax.swing.JLabel();
        jLabelSoftware = new javax.swing.JLabel();
        jLabelSeats = new javax.swing.JLabel();
        jComboBoxFunctional = new javax.swing.JComboBox<>();
        jComboBoxSoftware = new javax.swing.JComboBox<>();
        jComboBoxSeats = new javax.swing.JComboBox<>();
        jComboBoxNumber = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonSearch = new javax.swing.JButton();
        jButtonViewAll = new javax.swing.JButton();
        jPanelDB = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTaSamaya = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemPrint = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemAdd = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jMenuItemEdit = new javax.swing.JMenuItem();

        jDialogAddClass.setTitle("Добавить аудиторию");
        jDialogAddClass.setName("Добавить аудиторию"); // NOI18N
        jDialogAddClass.getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("Количество посадочных мест:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Функциональное назначение:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 0, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Установленное ПО:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 17, 0, 0);
        jPanel2.add(jLabel8, gridBagConstraints);

        jTextFieldNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 55, 0, 55);
        jPanel2.add(jTextFieldNumber, gridBagConstraints);

        jTextFieldSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeatsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 55, 0, 55);
        jPanel2.add(jTextFieldSeats, gridBagConstraints);

        jTextFieldFunctional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFunctionalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 55, 0, 55);
        jPanel2.add(jTextFieldFunctional, gridBagConstraints);

        jTextAreaSoftware.setColumns(20);
        jTextAreaSoftware.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSoftware);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.ipady = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 55, 6, 55);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        jLabel1.setText("Номер аудитории:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 15, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jButtonOk.setText("Ок");
        jButtonOk.setPreferredSize(new java.awt.Dimension(45, 50));
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 100, 0, 50);
        jPanel2.add(jButtonOk, gridBagConstraints);

        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 98);
        jPanel2.add(jButtonCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jDialogAddClass.getContentPane().add(jPanel2, gridBagConstraints);

        jDialogDeleteClass.setName("Удаление аудитории"); // NOI18N
        jDialogDeleteClass.getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Выберите номер аудитории:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 12);
        jPanel3.add(jLabel2, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 32, 0, 0);
        jPanel3.add(jComboBox1, gridBagConstraints);

        jButtonDeleteOk.setText("Ок");
        jButtonDeleteOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 12, 0);
        jPanel3.add(jButtonDeleteOk, gridBagConstraints);

        jButtonDeleteCancel.setText("Отмена");
        jButtonDeleteCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 12, 0);
        jPanel3.add(jButtonDeleteCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jDialogDeleteClass.getContentPane().add(jPanel3, gridBagConstraints);

        jDialogEditClass.getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Выберите номер аудитории:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 0);
        jPanel4.add(jLabel3, gridBagConstraints);

        jComboBoxSelectNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSelectNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 0, 0);
        jPanel4.add(jComboBoxSelectNumber, gridBagConstraints);

        jButtonFind.setText("Найти");
        jButtonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 13, 0, 0);
        jPanel4.add(jButtonFind, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 247;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        jPanel4.add(jSeparator1, gridBagConstraints);

        jLabel4.setText("Количество посадочных мест:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 0);
        jPanel4.add(jLabel4, gridBagConstraints);

        jTextFieldEditSeats.setText("jTextField1");
        jTextFieldEditSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditSeatsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 19, 0, 19);
        jPanel4.add(jTextFieldEditSeats, gridBagConstraints);

        jLabel5.setText("Функциональное назначение:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 0);
        jPanel4.add(jLabel5, gridBagConstraints);

        jTextFieldEditFunctional.setText("jTextField2");
        jTextFieldEditFunctional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditFunctionalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 19, 0, 19);
        jPanel4.add(jTextFieldEditFunctional, gridBagConstraints);

        jLabel9.setText("Установленное ПО:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 0);
        jPanel4.add(jLabel9, gridBagConstraints);

        jButtonEditOk.setText("Применить");
        jButtonEditOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        jPanel4.add(jButtonEditOk, gridBagConstraints);

        jButtonEditCancel.setText("Отмена");
        jButtonEditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 0);
        jPanel4.add(jButtonEditCancel, gridBagConstraints);

        jTextAreaEditSoftware.setColumns(20);
        jTextAreaEditSoftware.setRows(5);
        jScrollPane3.setViewportView(jTextAreaEditSoftware);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 19, 8, 19);
        jPanel4.add(jScrollPane3, gridBagConstraints);

        jDialogEditClass.getContentPane().add(jPanel4, new java.awt.GridBagConstraints());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accountin of classrooms ");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanelSearch.setLayout(new java.awt.GridBagLayout());

        jPanelFilters.setLayout(new java.awt.GridBagLayout());

        jLabelNumber.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabelNumber.setText("Номер аудитории:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanelFilters.add(jLabelNumber, gridBagConstraints);

        jLabelFunctional.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabelFunctional.setText("Функц. назначение:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanelFilters.add(jLabelFunctional, gridBagConstraints);

        jLabelSoftware.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabelSoftware.setText("Установленное ПО:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanelFilters.add(jLabelSoftware, gridBagConstraints);

        jLabelSeats.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabelSeats.setText("Количество мест:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanelFilters.add(jLabelSeats, gridBagConstraints);


        //КОСТЫЛЬ
        List<String> tmpArr=new ArrayList<>();
        for (int i=0;i<dt.size();i++){
            boolean flag=true;
            for (int j=0;j<tmpArr.size();j++){
                if(tmpArr.get(j).equals(dt.get(i).funcAud)){
                    flag=false;
                }
            }
            if (flag) {
                tmpArr.add(dt.get(i).funcAud);
            }
        }

        Collections.sort(tmpArr);
        tmpArr.add(0," - ");

        String[] func=new String[tmpArr.size()];
        tmpArr.toArray(func);

        jComboBoxFunctional.setModel(new javax.swing.DefaultComboBoxModel<>(func));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanelFilters.add(jComboBoxFunctional, gridBagConstraints);

        jComboBoxSoftware.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {" - ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanelFilters.add(jComboBoxSoftware, gridBagConstraints);

        //КОСТЫЛЬ
        tmpArr=new ArrayList<>();
        for (int i=0;i<dt.size();i++){
            boolean flag=true;
            for (int j=0;j<tmpArr.size();j++){
                if(tmpArr.get(j).equals(dt.get(i).plN)){
                    flag=false;
                }
            }
            if (flag) {
                tmpArr.add(dt.get(i).plN);
            }
        }

        Collections.sort(tmpArr);
        tmpArr.add(0," - ");

        String[] models=new String [tmpArr.size()];
        tmpArr.toArray(models);

        jComboBoxSeats.setModel(new javax.swing.DefaultComboBoxModel<>(models));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanelFilters.add(jComboBoxSeats, gridBagConstraints);

        //КОСТЫЛЬ
        tmpArr=new ArrayList<>();
        for (int i=0;i<dt.size();i++){
            boolean flag=true;
            for (int j=0;j<tmpArr.size();j++){
                if(tmpArr.get(j).equals(dt.get(i).audN)){
                    flag=false;
                }
            }
            if (flag) {
                tmpArr.add(dt.get(i).audN);
            }
        }

        Collections.sort(tmpArr);
        tmpArr.add(0," - ");

        String[] numbers=new String [tmpArr.size()];
        tmpArr.toArray(numbers);

        jComboBoxNumber.setModel(new javax.swing.DefaultComboBoxModel<>(numbers));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanelFilters.add(jComboBoxNumber, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        jPanelSearch.add(jPanelFilters, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonSearch.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jButtonSearch.setText("Поиск");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanel1.add(jButtonSearch, gridBagConstraints);

        jButtonViewAll.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jButtonViewAll.setText("Показать все");
        jButtonViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 383, 0, 0);
        jPanel1.add(jButtonViewAll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        jPanelSearch.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        jPanel5.add(jPanelSearch, gridBagConstraints);

        jPanelDB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelDB.setAutoscrolls(true);
        jPanelDB.setLayout(new java.awt.GridBagLayout());

        //КОСТЫЛЬ
        String[][]datAr=new String[dt.size()][4];
        for(int i=0;i< datAr.length;i++){
            datAr[i][0]=dt.get(i).audN;
            datAr[i][1]=dt.get(i).plN;
            datAr[i][2]=dt.get(i).funcAud;
            datAr[i][3]=dt.get(i).po;
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                datAr,
                new String [] {
                        "Номер удитории",
                        "Количество посадочных мест",
                        "Функциональное назначение",
                        "<html><center>Установленное<br/>программное обеспечение</center></html>"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            boolean[] canEdit = new boolean [] {
                    false,false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setRowHeight(18);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setRowSorter(new TableRowSorter<TableModel>(jTable1.getModel()));
        jTable1.getTableHeader().setPreferredSize(new Dimension(jTable1.getColumnModel().getTotalColumnWidth(),32));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanelDB.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel5.add(jPanelDB, gridBagConstraints);

        jTabbedPane2.addTab("Поиск", jPanel5);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        //TODO загрузить из БД заполняемость в этот чудный массив:
        Object [][] checks=new Object [][] {
                {null,
                        "X", null, null, null, null, null,
                        null, null, null, null, null, null,
                        null, null, null, null, null, null,
                        null, null, null, null, null, null,
                        null, null, null, null, null, null}
        };

        jTableTaSamaya.setModel(new javax.swing.table.DefaultTableModel(
                checks,
                new String [] {
                        " № аудитории",
                        "1", "2", "3", "4", "5", "6",
                        "1", "2", "3", "4", "5", "6",
                        "1", "2", "3", "4", "5", "6",
                        "1", "2", "3", "4", "5", "6",
                        "1", "2", "3", "4", "5", "6"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false,
                    true, true, true, true, true, true,
                    true, true, true, true, true, true,
                    true, true, true, true, true, true,
                    true, true, true, true, true, true,
                    true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTaSamaya.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableTaSamaya.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableTaSamaya);
        if (jTableTaSamaya.getColumnModel().getColumnCount() > 0) {
            jTableTaSamaya.getColumnModel().getColumn(0).setResizable(false);
            jTableTaSamaya.getColumnModel().getColumn(0).setPreferredWidth(600);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 762;
        gridBagConstraints.ipady = 338;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
        jPanel6.add(jScrollPane4, gridBagConstraints);

        jPanel7.setMinimumSize(new java.awt.Dimension(380, 20));
        jPanel7.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Пятница");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(237, 237, 237), new java.awt.Color(166, 166, 166)));
        jLabel10.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel10.setMinimumSize(new java.awt.Dimension(130, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        jPanel7.add(jLabel10, gridBagConstraints);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Среда");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(237, 237, 237), new java.awt.Color(166, 166, 166)));
        jLabel12.setMinimumSize(new java.awt.Dimension(130, 20));
        jLabel12.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        jPanel7.add(jLabel12, gridBagConstraints);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Вторник");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(237, 237, 237), new java.awt.Color(166, 166, 166)));
        jLabel13.setMinimumSize(new java.awt.Dimension(130, 20));
        jLabel13.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        jPanel7.add(jLabel13, gridBagConstraints);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Четверг");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(237, 237, 237), new java.awt.Color(166, 166, 166)));
        jLabel11.setMinimumSize(new java.awt.Dimension(130, 20));
        jLabel11.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        jPanel7.add(jLabel11, gridBagConstraints);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Понедельник");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(237, 237, 237), new java.awt.Color(166, 166, 166)));
        jLabel14.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel14.setMinimumSize(new java.awt.Dimension(130, 20));
        jLabel14.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel7.add(jLabel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 312;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 90, 0, 0);
        jPanel6.add(jPanel7, gridBagConstraints);

        jTabbedPane2.addTab("Занятость", jPanel6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jTabbedPane2, gridBagConstraints);

        jMenuFile.setText("Файл");
        jMenuFile.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N

        jMenuItemPrint.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jMenuItemPrint.setText("Печать");
        jMenuItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemPrint);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Редактирование списка");
        jMenuEdit.setBorderPainted(false);
        jMenuEdit.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N

        jMenuItemAdd.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jMenuItemAdd.setText("Добавить аудиторию");
        jMenuItemAdd.setBorderPainted(false);
        jMenuItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemAdd);

        jMenuItemDelete.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jMenuItemDelete.setText("Удалить");
        jMenuItemDelete.setBorderPainted(false);
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemDelete);

        jMenuItemEdit.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jMenuItemEdit.setText("Редактировать");
        jMenuItemEdit.setBorderPainted(false);
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemEdit);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>

    private void jMenuItemPrintActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (! jTable1.print()) {
                System.err.println("User cancelled printing");
            }
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }

    private void jMenuItemAddActionPerformed(java.awt.event.ActionEvent evt) {
        jDialogAddClass.setVisible(true);
    }

    private void jMenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        Object[] numbersOfClassrooms={"1","2","3"};//TODO массив с номерами аудиторий из бд, для выбора удаляемой
        String numberForDel = (String) JOptionPane.showInputDialog(this,
                "Выберите номер аудитории, \n"+"которую необходимо удалить:",
                "Удаление аудитории", JOptionPane.PLAIN_MESSAGE,
                null, numbersOfClassrooms,numbersOfClassrooms[0]);
        if ((numberForDel != null) && (numberForDel.length() > 0)) {
            //TODO манипуляции по удалению аудитории numberForDel из бд
            return;
        }
    }

    private void jMenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {
        jDialogEditClass.setVisible(true);
    }

    private void jButtonViewAllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO высветить все аудитории(SELECT *)
    }

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO высветить аудитории по фильтрам
    }

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO считываешь значения полей jDialogAddClass и добавляешь в БД новую аудиторию

        jDialogAddClass.setVisible(false);
    }

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
        jDialogAddClass.setVisible(false);
    }

    private void jTextFieldNumberActionPerformed(java.awt.event.ActionEvent evt) {}

    private void jTextFieldSeatsActionPerformed(java.awt.event.ActionEvent evt) {}

    private void jTextFieldFunctionalActionPerformed(java.awt.event.ActionEvent evt) {}

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {}

    private void jButtonDeleteOkActionPerformed(java.awt.event.ActionEvent evt) {}

    private void jButtonDeleteCancelActionPerformed(java.awt.event.ActionEvent evt) {}

    private void jComboBoxSelectNumberActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonFindActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO находишь аудиторию по номеру из поля jComboBoxSelectNumber и передаешь значения по аудитории соответствующим полям jTextFieldEditSeats, jTextFieldEditFunctional, jTextAreaEditSoftware
    }

    private void jTextFieldEditSeatsActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jTextFieldEditFunctionalActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jButtonEditOkActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO редактируешь аудиторию по номеру из поля jComboBoxSelectNumber и передаешь значения по аудитории в бд из соответствующих полей jTextFieldEditSeats, jTextFieldEditFunctional, jTextAreaEditSoftware

    }

    private void jButtonEditCancelActionPerformed(java.awt.event.ActionEvent evt) {
        jDialogEditClass.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName().toString());
                if ("CDE/Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


}
